#include "BOSIniMerger.hpp"
#include "PluginTypeResolver.hpp"
#include "StringUtil.hpp"

#include <nlohmann/json.hpp>

#include <algorithm>
#include <array>
#include <fstream>
#include <stdexcept>
#include <unordered_map>
#include <unordered_set>

using namespace std;
namespace fs = std::filesystem;

namespace {

// Written as the sole content of AIO_SWAP.ini's first line and of every blanked source-file
// stand-in - scan() skips any file starting with either, so a rescan never treats this tool's own
// previous output as a new source mod.
constexpr const char* AIO_HEADER_MARKER = "; Generated by BOSPriority";
constexpr const char* BLANK_MARKER = "; Blanked by BOSPriority - see AIO_SWAP.ini";

// Several real-world *_SWAP.ini exports start with a UTF-8 BOM (EF BB BF). Left unhandled, it
// glues itself to the first line's first byte, so a check like "line.front() == '['" on the
// file's very first section header silently fails - every line until the next section header (or
// the whole file, if it only has one section) then gets skipped as "stray line before any section
// header". Must be called right after opening the stream, before any getline().
void skipUtf8Bom(ifstream& f)
{
    constexpr array<unsigned char, 3> bom {0xEF, 0xBB, 0xBF};
    array<char, 3> buf {};
    const auto start = f.tellg();
    f.read(buf.data(), static_cast<streamsize>(buf.size()));
    if (f.gcount() == static_cast<streamsize>(buf.size())
        && static_cast<unsigned char>(buf[0]) == bom[0] && static_cast<unsigned char>(buf[1]) == bom[1]
        && static_cast<unsigned char>(buf[2]) == bom[2]) {
        return; // BOM consumed - stream stays positioned right after it
    }
    f.clear();
    f.seekg(start);
}

auto trim(string s) -> string
{
    while (!s.empty() && (s.back() == '\r' || s.back() == ' ' || s.back() == '\t')) {
        s.pop_back();
    }
    size_t start = 0;
    while (start < s.size() && (s[start] == ' ' || s[start] == '\t')) {
        ++start;
    }
    return s.substr(start);
}

auto firstField(const string& line) -> string
{
    const auto p = line.find('|');
    return p == string::npos ? line : line.substr(0, p);
}

// Returns the Nth (0-indexed) pipe-delimited field of a BOS line
// (origBaseID|swapBaseID|propertyOverrides|chance).
auto nthField(const string& line, size_t n) -> string
{
    size_t start = 0;
    for (size_t i = 0; i < n; ++i) {
        const auto p = line.find('|', start);
        if (p == string::npos) {
            return {};
        }
        start = p + 1;
    }
    const auto end = line.find('|', start);
    return end == string::npos ? line.substr(start) : line.substr(start, end - start);
}

// Mirrors BaseObjectSwapper's own Chance::Chance(const std::string&) parsing (Manager.cpp /
// RNG.cpp in powerof3/BaseObjectSwapper): a field only affects anything if it contains the
// substring "chance" (so "NONE" and anything else defaults to always-applies); the numeric value
// inside the parentheses is the chance percentage. The R/S/L letter only selects which RNG BOS
// seeds with at runtime - irrelevant here, we only need the value to tell a randomized pool apart
// from a deterministic swap.
auto parseChanceValue(const string& chanceField) -> float
{
    string lowerField = chanceField;
    ranges::transform(lowerField, lowerField.begin(), [](char c) { return static_cast<char>(tolower(static_cast<unsigned char>(c))); });
    if (lowerField.find("chance") == string::npos) {
        return 100.0F;
    }

    const auto openParen = chanceField.find('(');
    const auto closeParen = chanceField.find(')');
    if (openParen == string::npos || closeParen == string::npos || closeParen <= openParen + 1) {
        return 100.0F;
    }

    const string inner = chanceField.substr(openParen + 1, closeParen - openParen - 1);
    const auto comma = inner.find(',');
    const string valueStr = comma == string::npos ? inner : inner.substr(0, comma);

    try {
        return stof(valueStr);
    } catch (const exception&) {
        return 100.0F;
    }
}

auto isBosSwapIniFile(const fs::path& p) -> bool
{
    if (StringUtil::toLowerW(p.extension().wstring()) != L".ini") {
        return false;
    }
    const auto stem = StringUtil::toLowerW(p.stem().wstring());
    return stem.ends_with(L"_swap");
}

// True if this file is empty, or starts with one of this tool's own markers - i.e. it's this
// tool's own previous output, not a real source mod's ini.
auto isOwnOutput(const fs::path& file) -> bool
{
    ifstream f(file);
    if (!f.is_open()) {
        return true; // unreadable - treat as nothing to contribute, matches empty-file handling
    }
    skipUtf8Bom(f);

    string firstLine;
    if (!getline(f, firstLine)) {
        return true; // empty file
    }

    firstLine = trim(firstLine);
    return firstLine.empty() || firstLine.starts_with(AIO_HEADER_MARKER) || firstLine == BLANK_MARKER;
}

// Narrower than isOwnOutput() above: true only if the file actually carries one of this tool's own
// markers, NOT merely if it's empty (an empty *_SWAP.ini could just as easily belong to some other
// mod). Used only for countActiveOutputFiles()'s diagnostic, where a false positive would produce
// a misleading warning telling the user their Output mod is active when it might not be.
auto isKnownBosPriorityOutput(const fs::path& file) -> bool
{
    ifstream f(file);
    if (!f.is_open()) {
        return false;
    }
    skipUtf8Bom(f);

    string firstLine;
    if (!getline(f, firstLine)) {
        return false;
    }

    firstLine = trim(firstLine);
    return firstLine.starts_with(AIO_HEADER_MARKER) || firstLine == BLANK_MARKER;
}

auto discoverSourceFiles(const fs::path& gameDir) -> vector<fs::path>
{
    const auto dataDir = gameDir / L"Data";

    vector<fs::path> found;
    if (!fs::exists(dataDir) || !fs::is_directory(dataDir)) {
        return found;
    }

    for (const auto& entry : fs::directory_iterator(dataDir)) {
        if (entry.is_regular_file() && isBosSwapIniFile(entry.path()) && !isOwnOutput(entry.path())) {
            found.push_back(entry.path());
        }
    }

    // BOS's own default order: alphabetical, case-sensitive, last file wins.
    ranges::sort(found);
    return found;
}

// Parses a BOS key of the form "0xHHHHHH~PluginName.esp" into (localFormId, pluginName).
// Returns nullopt for anything else (bare EditorID, malformed hex, etc.) - PluginTypeResolver
// only supports hex FormID references.
auto parseFormIdRef(const string& key) -> optional<pair<uint32_t, string>>
{
    if (key.size() < 3 || key[0] != '0' || (key[1] != 'x' && key[1] != 'X')) {
        return nullopt;
    }

    const auto tildePos = key.find('~');
    if (tildePos == string::npos || tildePos <= 2) {
        return nullopt;
    }

    const string hexPart = key.substr(2, tildePos - 2);
    const string pluginName = key.substr(tildePos + 1);

    try {
        size_t consumed = 0;
        const auto formId = static_cast<uint32_t>(stoul(hexPart, &consumed, 16));
        if (consumed != hexPart.size()) {
            return nullopt;
        }
        return make_pair(formId, pluginName);
    } catch (const exception&) {
        return nullopt;
    }
}

auto storageKey(const SwapKey& swapKey) -> string
{
    return swapKey.section + "||" + swapKey.key;
}

// Splits a raw section string like "[Forms|FalkreathLocation]" or "[Forms|A,B]" into its prefix
// ("Forms") and location filter tokens ("FalkreathLocation", or ["A","B"]). An unfiltered section
// ("[Forms]", no '|') returns an empty token list.
auto parseSectionFilter(const string& rawSection) -> pair<string, vector<string>>
{
    string inner = rawSection;
    if (!inner.empty() && inner.front() == '[') {
        inner.erase(0, 1);
    }
    if (!inner.empty() && inner.back() == ']') {
        inner.pop_back();
    }

    const auto pipePos = inner.find('|');
    if (pipePos == string::npos) {
        return {inner, {}};
    }

    const string prefix = inner.substr(0, pipePos);
    const string filterPart = inner.substr(pipePos + 1);

    vector<string> tokens;
    size_t start = 0;
    while (start <= filterPart.size()) {
        const auto comma = filterPart.find(',', start);
        string token = comma == string::npos ? filterPart.substr(start) : filterPart.substr(start, comma - start);
        token = trim(token);
        if (!token.empty()) {
            tokens.push_back(token);
        }
        if (comma == string::npos) {
            break;
        }
        start = comma + 1;
    }
    return {prefix, tokens};
}

} // namespace

auto BOSIniMerger::scan(const fs::path& gameDir) -> vector<SwapKey>
{
    const auto files = discoverSourceFiles(gameDir);
    const auto dataDir = gameDir / L"Data";

    vector<SwapKey> result;
    unordered_map<string, size_t> keyIndex; // "section\x1Fkey" -> index into result
    PluginTypeResolver resolver;

    for (const auto& file : files) {
        ifstream f(file);
        if (!f.is_open()) {
            continue;
        }
        skipUtf8Bom(f);

        const string fileName = StringUtil::utf16ToUtf8(file.filename().wstring());
        string line;
        string section;
        string sectionPrefix;
        vector<string> sectionTokens; // location filter tokens after '|', empty if unfiltered
        while (getline(f, line)) {
            line = trim(line);
            if (line.empty() || line.front() == ';') {
                continue;
            }
            if (line.front() == '[') {
                // Tolerate a trailing inline comment after the closing bracket (e.g.
                // "[References] ; note") - without this, such a line falls through to be
                // misread as a data line under whatever section preceded it.
                if (const auto closeBracket = line.find(']'); closeBracket != string::npos) {
                    section = line.substr(0, closeBracket + 1);
                    tie(sectionPrefix, sectionTokens) = parseSectionFilter(section);
                    continue;
                }
            }
            if (section.empty()) {
                continue; // stray line before any section header
            }

            const string key = firstField(line);

            // A section can list several locations at once ("[Forms|A,B]") - BOS applies the same
            // swap if the ref is in EITHER. Comparing the raw section string verbatim would miss a
            // real conflict against another mod's "[Forms|A]" (same location A, different list
            // text) entirely, so each line is filed under one group PER listed location instead of
            // one group per raw section string - an unfiltered section files under a single
            // "no location filter" group, same as before.
            struct Target {
                string displaySection;
                string mapKey;
            };
            vector<Target> targets;
            if (sectionTokens.empty()) {
                targets.push_back({section, sectionPrefix + "\x1F\x1F" + key});
            } else {
                for (const auto& token : sectionTokens) {
                    string lowerToken = token;
                    ranges::transform(lowerToken, lowerToken.begin(),
                        [](char c) { return static_cast<char>(tolower(static_cast<unsigned char>(c))); });
                    targets.push_back(
                        {"[" + sectionPrefix + "|" + token + "]", sectionPrefix + "\x1F" + lowerToken + "\x1F" + key});
                }
            }

            for (const auto& target : targets) {
                size_t idx = 0;
                if (const auto it = keyIndex.find(target.mapKey); it != keyIndex.end()) {
                    idx = it->second;
                } else {
                    idx = result.size();
                    keyIndex[target.mapKey] = idx;

                    SwapKey swapKey;
                    swapKey.section = target.displaySection;
                    swapKey.key = key;
                    result.push_back(std::move(swapKey));
                }

                // Skip a line this same file already declared verbatim for this key (a copy-paste
                // artifact, seen in real exports) - nothing to decide between two candidates from
                // one file that would produce the same output either way. An identical line from a
                // DIFFERENT file is deliberately kept: merge() derives the set of originals to
                // blank from the recorded candidates, so dropping the second file here would leave
                // its ini live in the load order next to AIO_SWAP.ini - and since AIO_SWAP.ini
                // sorts near-first alphabetically, that surviving original would then beat the
                // user's chosen winner at runtime. SwapKey::isRealConflict() is what keeps these
                // identical-across-files candidates out of the conflict table.
                auto& candidates = result[idx].candidates;
                if (!ranges::any_of(candidates,
                        [&](const SwapEntry& e) { return e.line == line && e.sourceFile == fileName; })) {
                    candidates.push_back(SwapEntry {fileName, line});
                }
            }
        }
    }

    // Type comes from the swap TARGET (second field), not the key itself: for [References]
    // entries the key names a REFR (always resolves to "REFR", not useful to filter by), while
    // the swap target is always a base-object FormID. A single target field can list several
    // comma-separated alternatives (BOS picks one at runtime) - the first is representative
    // enough for classification. Shared by the winning-candidate lookup below (for
    // SwapKey::recordType) and the per-candidate lookup (for SwapEntry::targetMissing), since a
    // candidate whose target can't be resolved at all - wrong plugin name, or an EditorID nothing
    // defines - is exactly the same "unresolvable" case either way BOS would silently skip it.
    auto resolveTargetType = [&](const string& line) -> optional<string> {
        string targetField = nthField(line, 1);
        if (const auto comma = targetField.find(','); comma != string::npos) {
            targetField = targetField.substr(0, comma);
        }
        if (const auto parsed = parseFormIdRef(targetField)) {
            return resolver.resolveType(dataDir, parsed->second, parsed->first);
        }
        // Most real-world BOS ini exports reference a bare EditorID rather than a hex FormID - the
        // plugin that defines it isn't named here, so this falls back to a global EditorID index
        // built across every plugin in Data (see PluginTypeResolver).
        return resolver.resolveTypeByEditorId(dataDir, targetField);
    };

    for (auto& swapKey : result) {
        swapKey.selectedCandidate = static_cast<int>(swapKey.candidates.size()) - 1;
        const auto& winningLine = swapKey.candidates.back().line;

        swapKey.recordType = resolveTargetType(winningLine);
        for (auto& candidate : swapKey.candidates) {
            candidate.targetMissing = !resolveTargetType(candidate.line).has_value();
        }

        if (swapKey.candidates.size() > 1) {
            const float winningChance = parseChanceValue(nthField(winningLine, 3));
            swapKey.isChancePool = winningChance < 100.0F;
        }
    }

    return result;
}

auto BOSIniMerger::merge(const vector<SwapKey>& keys, const fs::path& outputFolder, bool dryRun) -> BosMergeStats
{
    BosMergeStats stats;

    vector<pair<string, vector<string>>> sections; // section -> lines, first-seen order
    unordered_map<string, size_t> sectionIndex;
    unordered_set<string> sourceFileNames;

    int excludedCount = 0;
    int selectedCount = 0;
    int expectedCount = 0;

    for (const auto& swapKey : keys) {
        stats.linesRead += static_cast<int>(swapKey.candidates.size());
        if (swapKey.isRealConflict() && !swapKey.excluded) {
            ++stats.keysOverridden;
        }
        for (const auto& candidate : swapKey.candidates) {
            sourceFileNames.insert(candidate.sourceFile);
        }

        if (swapKey.excluded) {
            ++excludedCount;
            continue;
        }

        size_t idx = 0;
        if (const auto it = sectionIndex.find(swapKey.section); it != sectionIndex.end()) {
            idx = it->second;
        } else {
            idx = sections.size();
            sectionIndex[swapKey.section] = idx;
            sections.push_back({swapKey.section, {}});
        }

        if (swapKey.isChancePool) {
            // Not a real conflict - BOS keeps every entry sharing this key and rolls between them
            // at runtime, so all of them belong in the output, unchanged.
            expectedCount += static_cast<int>(swapKey.candidates.size());
            for (const auto& candidate : swapKey.candidates) {
                sections[idx].second.push_back(candidate.line);
                ++selectedCount;
            }
            continue;
        }

        ++expectedCount;
        if (swapKey.selectedCandidate < 0
            || swapKey.selectedCandidate >= static_cast<int>(swapKey.candidates.size())) {
            continue; // defensive - malformed selection, completeness check below will catch it
        }

        sections[idx].second.push_back(swapKey.candidates[swapKey.selectedCandidate].line);
        ++selectedCount;
    }

    stats.filesRead = static_cast<int>(sourceFileNames.size());
    stats.linesWritten = selectedCount;

    // Completeness check: every non-excluded key must have contributed its expected line count
    // (one for a real conflict/non-conflict, every candidate for a chance pool). If not, something
    // is wrong - abort before touching any file rather than risk silently dropping a swap rule
    // when the originals get blanked below.
    if (selectedCount != expectedCount) {
        throw runtime_error("BOSIniMerger: completeness check failed (expected "
                             + to_string(expectedCount) + " line(s), got " + to_string(selectedCount)
                             + ") - aborting without writing anything.");
    }

    if (dryRun) {
        return stats;
    }

    fs::create_directories(outputFolder);

    // Every file is first written to a ".tmp" sibling with exceptions enabled, so a write failure
    // (read-only folder, disk full, file locked by another program) throws instead of silently
    // leaving a truncated/empty file. Only once every temp write has fully succeeded do we rename
    // them all into place - so an I/O failure partway through can never leave the output folder in
    // a state where AIO_SWAP.ini is missing/broken but the originals are already blanked, or where
    // only some originals got blanked.
    vector<pair<fs::path, fs::path>> pendingRenames; // temp path -> final path

    auto writeTempFile = [&](const fs::path& finalPath, const auto& writeBody) {
        auto tempPath = finalPath;
        tempPath += L".tmp";
        try {
            ofstream file(tempPath, ios::binary);
            file.exceptions(ios::failbit | ios::badbit);
            writeBody(file);
            file.close();
        } catch (const exception&) {
            error_code ec;
            fs::remove(tempPath, ec);
            for (const auto& [temp, unused] : pendingRenames) {
                fs::remove(temp, ec);
            }
            throw runtime_error("BOSIniMerger: failed to write " + finalPath.filename().string()
                                 + " to the output folder - aborting without touching any original ini file.");
        }
        pendingRenames.emplace_back(std::move(tempPath), finalPath);
    };

    writeTempFile(outputFolder / L"AIO_SWAP.ini", [&](ostream& out) {
        out << AIO_HEADER_MARKER << " - do not hand-edit, re-run the tool instead\n";
        out << "; " << stats.filesRead << " source ini file(s) merged, " << excludedCount << " key(s) excluded\n";
        out << "; This file is the single source of truth - every original *_SWAP.ini listed below\n";
        out << "; has been replaced with an empty stand-in in this same output folder.\n\n";

        for (const auto& [section, lines] : sections) {
            out << section << "\n";
            for (const auto& line : lines) {
                out << line << "\n";
            }
            out << "\n";
        }
    });

    for (const auto& name : sourceFileNames) {
        // A source mod can legitimately ship a file called AIO_SWAP.ini itself (the companion
        // xEdit script "BOS AIO Patcher.pas" produces one). Its content has already been merged
        // into the AIO_SWAP.ini written just above, which IS its stand-in - queueing a blank for
        // it would target the same path twice: the blank would clobber the merged temp file, and
        // the second rename of an already-consumed temp would fail, leaving the output folder with
        // an AIO_SWAP.ini containing nothing but the blank marker.
        if (StringUtil::toLowerW(StringUtil::utf8ToUtf16(name)) == L"aio_swap.ini") {
            continue;
        }
        writeTempFile(outputFolder / StringUtil::utf8ToUtf16(name),
            [](ostream& out) { out << BLANK_MARKER << "\n"; });
    }

    for (const auto& [temp, final] : pendingRenames) {
        error_code ec;
        fs::rename(temp, final, ec);
        if (ec) {
            throw runtime_error("BOSIniMerger: failed to finalize " + final.filename().string()
                                 + " in the output folder - some files may be left as .tmp; re-run the tool.");
        }
    }

    return stats;
}

void BOSIniMerger::applyDecisions(vector<SwapKey>& keys, const fs::path& decisionsFile)
{
    if (!fs::exists(decisionsFile)) {
        return;
    }

    nlohmann::json json;
    try {
        ifstream f(decisionsFile);
        json = nlohmann::json::parse(f);
    } catch (const exception&) {
        return; // corrupt/unreadable - treat like no saved decisions rather than fail the scan
    }

    for (auto& swapKey : keys) {
        if (!swapKey.isRealConflict()) {
            continue;
        }

        const auto it = json.find(storageKey(swapKey));
        if (it == json.end()) {
            continue;
        }

        if (it->contains("excluded") && (*it)["excluded"].is_boolean()) {
            swapKey.excluded = (*it)["excluded"].get<bool>();
        }
        if (it->contains("winnerFile") && (*it)["winnerFile"].is_string()) {
            const string winnerFile = (*it)["winnerFile"].get<string>();
            for (size_t i = 0; i < swapKey.candidates.size(); ++i) {
                if (swapKey.candidates[i].sourceFile == winnerFile) {
                    swapKey.selectedCandidate = static_cast<int>(i);
                    break;
                }
            }
        }
        swapKey.userDecided = true;
    }
}

void BOSIniMerger::saveDecisions(const vector<SwapKey>& keys, const fs::path& decisionsFile)
{
    auto json = nlohmann::json::object();
    for (const auto& swapKey : keys) {
        if (!swapKey.isRealConflict() || !swapKey.userDecided) {
            // Not shown/editable in the conflict table, or nobody has actually decided it -
            // persisting its arbitrary default would freeze it as if it were a real choice (see
            // SwapKey::userDecided's doc comment).
            continue;
        }

        json[storageKey(swapKey)] = {
            {"winnerFile",
             swapKey.excluded ? string {} : swapKey.candidates[static_cast<size_t>(swapKey.selectedCandidate)].sourceFile},
            {"excluded", swapKey.excluded},
        };
    }

    fs::create_directories(decisionsFile.parent_path());
    try {
        ofstream out(decisionsFile);
        out.exceptions(ios::failbit | ios::badbit);
        out << json.dump(2);
    } catch (const exception&) {
        // Losing this file only means saved conflict decisions won't be remembered next run - not
        // worth aborting generation over, but worth not pretending it silently succeeded either.
        throw runtime_error("BOSIniMerger: failed to write " + decisionsFile.filename().string());
    }
}

void BOSIniMerger::applyTypePriorities(vector<SwapKey>& keys, const map<string, vector<string>>& priorities)
{
    if (priorities.empty()) {
        return;
    }

    for (auto& swapKey : keys) {
        if (!swapKey.isRealConflict() || swapKey.excluded) {
            continue;
        }

        auto it = priorities.find(swapKey.recordType.value_or("Unknown"));
        if (it == priorities.end()) {
            it = priorities.find("All Types");
        }
        if (it == priorities.end()) {
            continue;
        }

        // Walked last-to-first: the stored list is "top of the on-screen list first, bottom
        // last", and the bottom entry is the one meant to win - same convention as a mod manager's
        // own load order, where the mod lower in the list overwrites the ones above it.
        for (auto fileIt = it->second.rbegin(); fileIt != it->second.rend(); ++fileIt) {
            const auto candidate
                = ranges::find_if(swapKey.candidates, [&](const SwapEntry& e) { return e.sourceFile == *fileIt; });
            if (candidate != swapKey.candidates.end()) {
                swapKey.selectedCandidate = static_cast<int>(candidate - swapKey.candidates.begin());
                break;
            }
        }
    }
}

void BOSIniMerger::saveTypePriorities(const map<string, vector<string>>& priorities, const fs::path& rankingFile)
{
    auto json = nlohmann::json::object();
    for (const auto& [type, files] : priorities) {
        json[type] = files;
    }

    fs::create_directories(rankingFile.parent_path());
    try {
        ofstream out(rankingFile);
        out.exceptions(ios::failbit | ios::badbit);
        out << json.dump(2);
    } catch (const exception&) {
        throw runtime_error("BOSIniMerger: failed to write " + rankingFile.filename().string());
    }
}

auto BOSIniMerger::loadTypePriorities(const fs::path& rankingFile) -> map<string, vector<string>>
{
    map<string, vector<string>> result;
    if (!fs::exists(rankingFile)) {
        return result;
    }

    try {
        ifstream f(rankingFile);
        const auto json = nlohmann::json::parse(f);
        for (auto it = json.begin(); it != json.end(); ++it) {
            if (!it.value().is_array()) {
                continue;
            }
            vector<string> files;
            for (const auto& entry : it.value()) {
                if (entry.is_string()) {
                    files.push_back(entry.get<string>());
                }
            }
            result[it.key()] = std::move(files);
        }
    } catch (const exception&) {
        return {}; // corrupt/unreadable - treat like no saved ranking rather than fail the scan
    }
    return result;
}

auto BOSIniMerger::countActiveOutputFiles(const fs::path& gameDir) -> int
{
    const auto dataDir = gameDir / L"Data";
    if (!fs::exists(dataDir) || !fs::is_directory(dataDir)) {
        return 0;
    }

    int count = 0;
    for (const auto& entry : fs::directory_iterator(dataDir)) {
        if (entry.is_regular_file() && isBosSwapIniFile(entry.path()) && isKnownBosPriorityOutput(entry.path())) {
            ++count;
        }
    }
    return count;
}
