#include "BOSIniMerger.hpp"
#include "PluginTypeResolver.hpp"
#include "StringUtil.hpp"

#include <nlohmann/json.hpp>

#include <algorithm>
#include <fstream>
#include <stdexcept>
#include <unordered_map>
#include <unordered_set>

using namespace std;
namespace fs = std::filesystem;

namespace {

// Written as the sole content of AIO_SWAP.ini's first line and of every blanked source-file
// stand-in - scan() skips any file starting with either, so a rescan never treats this tool's own
// previous output as a new source mod.
constexpr const char* AIO_HEADER_MARKER = "; Generated by BOSPriority";
constexpr const char* BLANK_MARKER = "; Blanked by BOSPriority - see AIO_SWAP.ini";

auto trim(string s) -> string
{
    while (!s.empty() && (s.back() == '\r' || s.back() == ' ' || s.back() == '\t')) {
        s.pop_back();
    }
    size_t start = 0;
    while (start < s.size() && (s[start] == ' ' || s[start] == '\t')) {
        ++start;
    }
    return s.substr(start);
}

auto firstField(const string& line) -> string
{
    const auto p = line.find('|');
    return p == string::npos ? line : line.substr(0, p);
}

// Returns the Nth (0-indexed) pipe-delimited field of a BOS line
// (origBaseID|swapBaseID|propertyOverrides|chance).
auto nthField(const string& line, size_t n) -> string
{
    size_t start = 0;
    for (size_t i = 0; i < n; ++i) {
        const auto p = line.find('|', start);
        if (p == string::npos) {
            return {};
        }
        start = p + 1;
    }
    const auto end = line.find('|', start);
    return end == string::npos ? line.substr(start) : line.substr(start, end - start);
}

// Mirrors BaseObjectSwapper's own Chance::Chance(const std::string&) parsing (Manager.cpp /
// RNG.cpp in powerof3/BaseObjectSwapper): a field only affects anything if it contains the
// substring "chance" (so "NONE" and anything else defaults to always-applies); the numeric value
// inside the parentheses is the chance percentage. The R/S/L letter only selects which RNG BOS
// seeds with at runtime - irrelevant here, we only need the value to tell a randomized pool apart
// from a deterministic swap.
auto parseChanceValue(const string& chanceField) -> float
{
    if (chanceField.find("chance") == string::npos) {
        return 100.0F;
    }

    const auto openParen = chanceField.find('(');
    const auto closeParen = chanceField.find(')');
    if (openParen == string::npos || closeParen == string::npos || closeParen <= openParen + 1) {
        return 100.0F;
    }

    const string inner = chanceField.substr(openParen + 1, closeParen - openParen - 1);
    const auto comma = inner.find(',');
    const string valueStr = comma == string::npos ? inner : inner.substr(0, comma);

    try {
        return stof(valueStr);
    } catch (const exception&) {
        return 100.0F;
    }
}

auto isBosSwapIniFile(const fs::path& p) -> bool
{
    if (StringUtil::toLowerW(p.extension().wstring()) != L".ini") {
        return false;
    }
    const auto stem = StringUtil::toLowerW(p.stem().wstring());
    return stem.ends_with(L"_swap");
}

// True if this file is empty, or starts with one of this tool's own markers - i.e. it's this
// tool's own previous output, not a real source mod's ini.
auto isOwnOutput(const fs::path& file) -> bool
{
    ifstream f(file);
    if (!f.is_open()) {
        return true; // unreadable - treat as nothing to contribute, matches empty-file handling
    }

    string firstLine;
    if (!getline(f, firstLine)) {
        return true; // empty file
    }

    firstLine = trim(firstLine);
    return firstLine.empty() || firstLine.starts_with(AIO_HEADER_MARKER) || firstLine == BLANK_MARKER;
}

auto discoverSourceFiles(const fs::path& gameDir) -> vector<fs::path>
{
    const auto dataDir = gameDir / L"Data";

    vector<fs::path> found;
    if (!fs::exists(dataDir) || !fs::is_directory(dataDir)) {
        return found;
    }

    for (const auto& entry : fs::directory_iterator(dataDir)) {
        if (entry.is_regular_file() && isBosSwapIniFile(entry.path()) && !isOwnOutput(entry.path())) {
            found.push_back(entry.path());
        }
    }

    // BOS's own default order: alphabetical, case-sensitive, last file wins.
    ranges::sort(found);
    return found;
}

// Parses a BOS key of the form "0xHHHHHH~PluginName.esp" into (localFormId, pluginName).
// Returns nullopt for anything else (bare EditorID, malformed hex, etc.) - PluginTypeResolver
// only supports hex FormID references.
auto parseFormIdRef(const string& key) -> optional<pair<uint32_t, string>>
{
    if (key.size() < 3 || key[0] != '0' || (key[1] != 'x' && key[1] != 'X')) {
        return nullopt;
    }

    const auto tildePos = key.find('~');
    if (tildePos == string::npos || tildePos <= 2) {
        return nullopt;
    }

    const string hexPart = key.substr(2, tildePos - 2);
    const string pluginName = key.substr(tildePos + 1);

    try {
        size_t consumed = 0;
        const auto formId = static_cast<uint32_t>(stoul(hexPart, &consumed, 16));
        if (consumed != hexPart.size()) {
            return nullopt;
        }
        return make_pair(formId, pluginName);
    } catch (const exception&) {
        return nullopt;
    }
}

auto storageKey(const SwapKey& swapKey) -> string
{
    return swapKey.section + "||" + swapKey.key;
}

} // namespace

auto BOSIniMerger::scan(const fs::path& gameDir) -> vector<SwapKey>
{
    const auto files = discoverSourceFiles(gameDir);
    const auto dataDir = gameDir / L"Data";

    vector<SwapKey> result;
    unordered_map<string, size_t> keyIndex; // "section\x1Fkey" -> index into result
    PluginTypeResolver resolver;

    for (const auto& file : files) {
        ifstream f(file);
        if (!f.is_open()) {
            continue;
        }

        const string fileName = file.filename().string();
        string line;
        string section;
        while (getline(f, line)) {
            line = trim(line);
            if (line.empty() || line.front() == ';') {
                continue;
            }
            if (line.front() == '[' && line.back() == ']') {
                section = line;
                continue;
            }
            if (section.empty()) {
                continue; // stray line before any section header
            }

            const string key = firstField(line);
            const string mapKey = section + '\x1F' + key;

            size_t idx = 0;
            if (const auto it = keyIndex.find(mapKey); it != keyIndex.end()) {
                idx = it->second;
            } else {
                idx = result.size();
                keyIndex[mapKey] = idx;

                SwapKey swapKey;
                swapKey.section = section;
                swapKey.key = key;
                result.push_back(std::move(swapKey));
            }

            // Skip exact duplicate lines for this key (same text, whether repeated within one
            // file by mistake or coincidentally identical across two) - nothing to decide between
            // two candidates that would produce the same output either way.
            auto& candidates = result[idx].candidates;
            if (!ranges::any_of(candidates, [&](const SwapEntry& e) { return e.line == line; })) {
                candidates.push_back(SwapEntry {fileName, line});
            }
        }
    }

    for (auto& swapKey : result) {
        swapKey.selectedCandidate = static_cast<int>(swapKey.candidates.size()) - 1;
        const auto& winningLine = swapKey.candidates.back().line;

        // Type comes from the swap TARGET (second field), not the key itself: for [References]
        // entries the key names a REFR (always resolves to "REFR", not useful to filter by),
        // while the swap target is always a base-object FormID. A single target field can list
        // several comma-separated alternatives (BOS picks one at runtime) - the first is
        // representative enough for classification.
        string targetField = nthField(winningLine, 1);
        if (const auto comma = targetField.find(','); comma != string::npos) {
            targetField = targetField.substr(0, comma);
        }
        if (const auto parsed = parseFormIdRef(targetField)) {
            swapKey.recordType = resolver.resolveType(dataDir, parsed->second, parsed->first);
        }

        if (swapKey.candidates.size() > 1) {
            const float winningChance = parseChanceValue(nthField(winningLine, 3));
            swapKey.isChancePool = winningChance < 100.0F;
        }
    }

    return result;
}

auto BOSIniMerger::merge(const vector<SwapKey>& keys, const fs::path& outputFolder, bool dryRun) -> BosMergeStats
{
    BosMergeStats stats;

    vector<pair<string, vector<string>>> sections; // section -> lines, first-seen order
    unordered_map<string, size_t> sectionIndex;
    unordered_set<string> sourceFileNames;

    int excludedCount = 0;
    int selectedCount = 0;
    int expectedCount = 0;

    for (const auto& swapKey : keys) {
        stats.linesRead += static_cast<int>(swapKey.candidates.size());
        if (swapKey.candidates.size() > 1 && !swapKey.isChancePool && !swapKey.excluded) {
            ++stats.keysOverridden;
        }
        for (const auto& candidate : swapKey.candidates) {
            sourceFileNames.insert(candidate.sourceFile);
        }

        if (swapKey.excluded) {
            ++excludedCount;
            continue;
        }

        size_t idx = 0;
        if (const auto it = sectionIndex.find(swapKey.section); it != sectionIndex.end()) {
            idx = it->second;
        } else {
            idx = sections.size();
            sectionIndex[swapKey.section] = idx;
            sections.push_back({swapKey.section, {}});
        }

        if (swapKey.isChancePool) {
            // Not a real conflict - BOS keeps every entry sharing this key and rolls between them
            // at runtime, so all of them belong in the output, unchanged.
            expectedCount += static_cast<int>(swapKey.candidates.size());
            for (const auto& candidate : swapKey.candidates) {
                sections[idx].second.push_back(candidate.line);
                ++selectedCount;
            }
            continue;
        }

        ++expectedCount;
        if (swapKey.selectedCandidate < 0
            || swapKey.selectedCandidate >= static_cast<int>(swapKey.candidates.size())) {
            continue; // defensive - malformed selection, completeness check below will catch it
        }

        sections[idx].second.push_back(swapKey.candidates[swapKey.selectedCandidate].line);
        ++selectedCount;
    }

    stats.filesRead = static_cast<int>(sourceFileNames.size());
    stats.linesWritten = selectedCount;

    // Completeness check: every non-excluded key must have contributed its expected line count
    // (one for a real conflict/non-conflict, every candidate for a chance pool). If not, something
    // is wrong - abort before touching any file rather than risk silently dropping a swap rule
    // when the originals get blanked below.
    if (selectedCount != expectedCount) {
        throw runtime_error("BOSIniMerger: completeness check failed (expected "
                             + to_string(expectedCount) + " line(s), got " + to_string(selectedCount)
                             + ") - aborting without writing anything.");
    }

    if (dryRun) {
        return stats;
    }

    fs::create_directories(outputFolder);

    ofstream out(outputFolder / L"AIO_SWAP.ini");
    out << AIO_HEADER_MARKER << " - do not hand-edit, re-run the tool instead\n";
    out << "; " << stats.filesRead << " source ini file(s) merged, " << excludedCount << " key(s) excluded\n";
    out << "; This file is the single source of truth - every original *_SWAP.ini listed below\n";
    out << "; has been replaced with an empty stand-in in this same output folder.\n\n";

    for (const auto& [section, lines] : sections) {
        out << section << "\n";
        for (const auto& line : lines) {
            out << line << "\n";
        }
        out << "\n";
    }
    out.close();

    for (const auto& name : sourceFileNames) {
        ofstream blank(outputFolder / StringUtil::utf8ToUtf16(name));
        blank << BLANK_MARKER << "\n";
    }

    return stats;
}

void BOSIniMerger::applyDecisions(vector<SwapKey>& keys, const fs::path& decisionsFile)
{
    if (!fs::exists(decisionsFile)) {
        return;
    }

    nlohmann::json json;
    try {
        ifstream f(decisionsFile);
        json = nlohmann::json::parse(f);
    } catch (const exception&) {
        return; // corrupt/unreadable - treat like no saved decisions rather than fail the scan
    }

    for (auto& swapKey : keys) {
        if (swapKey.candidates.size() < 2 || swapKey.isChancePool) {
            continue;
        }

        const auto it = json.find(storageKey(swapKey));
        if (it == json.end()) {
            continue;
        }

        if (it->contains("excluded") && (*it)["excluded"].is_boolean()) {
            swapKey.excluded = (*it)["excluded"].get<bool>();
        }
        if (it->contains("winnerFile") && (*it)["winnerFile"].is_string()) {
            const string winnerFile = (*it)["winnerFile"].get<string>();
            for (size_t i = 0; i < swapKey.candidates.size(); ++i) {
                if (swapKey.candidates[i].sourceFile == winnerFile) {
                    swapKey.selectedCandidate = static_cast<int>(i);
                    break;
                }
            }
        }
    }
}

void BOSIniMerger::saveDecisions(const vector<SwapKey>& keys, const fs::path& decisionsFile)
{
    auto json = nlohmann::json::object();
    for (const auto& swapKey : keys) {
        if (swapKey.candidates.size() < 2 || swapKey.isChancePool) {
            continue; // nothing to persist - not shown/editable in the conflict table
        }

        json[storageKey(swapKey)] = {
            {"winnerFile",
             swapKey.excluded ? string {} : swapKey.candidates[static_cast<size_t>(swapKey.selectedCandidate)].sourceFile},
            {"excluded", swapKey.excluded},
        };
    }

    fs::create_directories(decisionsFile.parent_path());
    ofstream out(decisionsFile);
    out << json.dump(2);
}
