#include "BOSIniMerger.hpp"
#include "StringUtil.hpp"

#include <algorithm>
#include <fstream>
#include <unordered_map>

using namespace std;
namespace fs = std::filesystem;

namespace {

struct SectionData {
    string header;
    vector<string> keys; // insertion order
    vector<string> lines; // parallel to keys
    unordered_map<string, size_t> keyIndex;
};

auto trim(string s) -> string
{
    while (!s.empty() && (s.back() == '\r' || s.back() == ' ' || s.back() == '\t')) {
        s.pop_back();
    }
    size_t start = 0;
    while (start < s.size() && (s[start] == ' ' || s[start] == '\t')) {
        ++start;
    }
    return s.substr(start);
}

auto firstField(const string& line) -> string
{
    const auto p = line.find('|');
    return p == string::npos ? line : line.substr(0, p);
}

auto isBosSwapIniFile(const fs::path& p) -> bool
{
    if (StringUtil::toLowerW(p.extension().wstring()) != L".ini") {
        return false;
    }
    const auto stem = StringUtil::toLowerW(p.stem().wstring());
    return stem.ends_with(L"_swap");
}

} // namespace

auto BOSIniMerger::discoverIniFiles(const fs::path& gameDir) -> vector<fs::path>
{
    const auto bosDir = gameDir / L"Data" / L"SKSE" / L"Plugins" / L"BaseObjectSwapper";

    vector<fs::path> found;
    if (!fs::exists(bosDir) || !fs::is_directory(bosDir)) {
        return found;
    }

    for (const auto& entry : fs::directory_iterator(bosDir)) {
        if (entry.is_regular_file() && isBosSwapIniFile(entry.path())) {
            found.push_back(entry.path());
        }
    }

    // BOS's own default order: alphabetical, case-sensitive, last file wins.
    ranges::sort(found);
    return found;
}

auto BOSIniMerger::merge(const vector<fs::path>& filesInApplyOrder,
                          const fs::path& outputFolder,
                          bool dryRun) -> BosMergeStats
{
    BosMergeStats stats;

    vector<SectionData> sections;
    unordered_map<string, size_t> sectionIndex;

    auto addLine = [&](const string& sectionHeader, const string& key, const string& line) {
        size_t idx = 0;
        if (const auto it = sectionIndex.find(sectionHeader); it != sectionIndex.end()) {
            idx = it->second;
        } else {
            idx = sections.size();
            sectionIndex[sectionHeader] = idx;
            sections.push_back(SectionData{sectionHeader, {}, {}, {}});
        }

        auto& section = sections[idx];
        if (const auto keyIt = section.keyIndex.find(key); keyIt != section.keyIndex.end()) {
            section.lines[keyIt->second] = line;
            ++stats.keysOverridden;
        } else {
            section.keyIndex[key] = section.keys.size();
            section.keys.push_back(key);
            section.lines.push_back(line);
        }
    };

    for (const auto& file : filesInApplyOrder) {
        ifstream f(file);
        if (!f.is_open()) {
            continue;
        }

        string line;
        string section;
        while (getline(f, line)) {
            line = trim(line);
            if (line.empty() || line.front() == ';') {
                continue;
            }
            if (line.front() == '[' && line.back() == ']') {
                section = line;
                continue;
            }
            if (section.empty()) {
                continue; // stray line before any section header
            }

            addLine(section, firstField(line), line);
            ++stats.linesRead;
        }
        ++stats.filesRead;
    }

    for (const auto& section : sections) {
        stats.linesWritten += static_cast<int>(section.lines.size());
    }

    if (dryRun) {
        return stats;
    }

    fs::create_directories(outputFolder);
    ofstream out(outputFolder / L"AIO_SWAP.ini");
    out << "; Generated by BOSPriority - do not hand-edit, re-run the tool instead\n";
    out << "; " << stats.filesRead << " source ini file(s) merged in your chosen priority order\n";
    out << "; Note: BOS itself also merges its own *_SWAP.ini files at runtime (alphabetical,\n";
    out << "; last file wins). This tool's value is letting you pick that order explicitly\n";
    out << "; instead of relying on filenames.\n\n";

    for (const auto& section : sections) {
        out << section.header << "\n";
        for (const auto& line : section.lines) {
            out << line << "\n";
        }
        out << "\n";
    }

    return stats;
}
